config/routes.rb
Rails.application.routes.draw do

  resources :guestbooks

  root 'static_page#index'
  get 'wedding_party', to: 'static_page#wedding_party'
  get 'wedding_details', to: 'static_page#wedding_details'
  get 'proposal', to: 'static_page#proposal'
  get 'registry', to: 'static_page#registry'
  get 'enter_code', to: 'rsvps#enter_code'
  get 'can_attend', to: 'static_page#rsvp_can_attend'
  get 'cannot_attend', to: 'static_page#rsvp_cannot_attend'
  
  resources :rsvps do
    post 'find_code'
    get 'update_rsvp'
    post 'update'
  end

end

app/models/guestbook.rb
class Guestbook < ActiveRecord::Base
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  before_action :set_guestbook, only: [:show, :edit, :update, :destroy]

  # GET /guestbooks
  # GET /guestbooks.json
  def index
    @guestbooks = Guestbook.all.reverse
  end

  # GET /guestbooks/new
  def new
    @guestbook = Guestbook.new
  end

  # POST /guestbooks
  # POST /guestbooks.json
  def create
    @guestbook = Guestbook.new(guestbook_params)

    respond_to do |format|
      if @guestbook.save
        format.html { redirect_to guestbooks_path, notice: 'Guestbook entry was successfully created.' }
        format.json { render :index, status: :created, location: @guestbook }
      else
        format.html { render :new }
        format.json { render json: @guestbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guestbooks/1
  # DELETE /guestbooks/1.json
  def destroy
    @guestbook.destroy
    respond_to do |format|
      format.html { redirect_to guestbooks_url, notice: 'Guestbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guestbook
      @guestbook = Guestbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guestbook_params
      params.require(:guestbook).permit(:name, :message)
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  #before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to enter_code_path
  end

  def enter_code
    @rsvp = Rsvp.new
    @error = flash[:error]
  end

  def create
    confirmation_code = params['rsvp']['confirmation_code'];
     @rsvp = Rsvp.where({confirmation_code: confirmation_code.upcase}).first

    respond_to do |format|
      if @rsvp
        format.html { redirect_to rsvp_update_rsvp_url(@rsvp.confirmation_code) }
        format.json { render :index, status: :created, location: @rsvp }
      else
        format.html { redirect_to enter_code_path, notice: 'Could not find rsvp with that code!  If you entered your code correctly, just send the RSVP back in the envelope.  Otherwise, please try again.'  }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_rsvp
      @rsvp = Rsvp.where({confirmation_code: params[:rsvp_id]}).first
  end

  def update
      @rsvp = Rsvp.find(params[:id])

      @rsvp.has_responded = true

    respond_to do |format|
      if @rsvp.update(rsvp_params)
        if @rsvp.num_attending > @rsvp.max_attending
          format.html { redirect_to rsvp_update_rsvp_url(@rsvp.confirmation_code), notice: "You can only bring #{@rsvp.max_attending} people.  If you feel this is in error, please contact Jill or Ryan." }
          format.json { render :index, status: :created, location: @rsvp }
        elsif @rsvp.can_attend 
          format.html { redirect_to can_attend_path, notice: 'Successfully rsvped' }
          format.json { render :index, status: :created, location: @rsvp }
        else
          format.html { redirect_to cannot_attend_path, notice: 'Successfully rsvped' }
          format.json { render :index, status: :created, location: @rsvp }
        end
      else
        format.html { redirect_to enter_code_path, error: 'Could not find rsvp with that code!'  }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end


  # # GET /rsvps/1
  # # GET /rsvps/1.json
  # def show
  # end

  # # GET /rsvps/new
  # def new
  #   @rsvp = Rsvp.new
  # end

  # # GET /rsvps/1/edit
  # def edit
  # end

  # # POST /rsvps
  # # POST /rsvps.json
  # def create
  #   @rsvp = Rsvp.new(rsvp_params)

  #   respond_to do |format|
  #     if @rsvp.save
  #       format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
  #       format.json { render :show, status: :created, location: @rsvp }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @rsvp.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /rsvps/1
  # # PATCH/PUT /rsvps/1.json
  # def update
  #   respond_to do |format|
  #     if @rsvp.update(rsvp_params)
  #       format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @rsvp }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @rsvp.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /rsvps/1
  # # DELETE /rsvps/1.json
  # def destroy
  #   @rsvp.destroy
  #   respond_to do |format|
  #     format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.require(:rsvp).permit(:name, :confirmation_code, :can_attend, :num_attending, :messages)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index

  end

  def wedding_details

  end

  def proposal

  end

  def wedding_party

  end

  def registry

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/guestbooks/_form.html.erb
<%= form_for(@guestbook) do |f| %>
  <% if @guestbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guestbook.errors.count, "error") %> prohibited this guestbook from being saved:</h2>

      <ul>
      <% @guestbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Write in Guestbook" %>
  </div>
<% end %>

app/views/guestbooks/index.html.erb
<div class='container'>   
  <div class='page-header'>
     <h1 style="font-family: 'Pacifico', cursive;">Guestbook</h1>
  </div>
</div>


<div class='container'>
<div class='row'>

<div class='col-lg-10'><p>Please sign our guestbook!</p></div>
<div class='col-lg-2'><%= link_to 'Write a Guestbook Entry', new_guestbook_path, :class => 'btn btn-default' %></div>
</div>
<br />

    <% @guestbooks.each do |guestbook| %>

      <div class='panel panel-default'>
         <div class='panel-heading'>
            <h3 class='panel-title'><%= guestbook.name %> - <%= time_ago_in_words(guestbook.created_at) %> ago</h3>
         </div>
         <div class='panel-default'>
         <div class='container'>
            <p><%= guestbook.message %></p>
            </div>
         </div>
      </div>
    <% end %>
</div>

app/views/guestbooks/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-10' style="font-family: 'Pacifico', cursive; font-size: 3em;">Write guestbook entry</div>
     <div class='col-lg-2'><%= link_to 'Back', guestbooks_path, :class => 'btn btn-default' %></div>
  </div>

<%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jill + Ryan are getting married!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css' />
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" style='width: 100%; text-align:center;'>
        <li style='float:none; display: inline-block;'><%= link_to "Wedding Details", wedding_details_path %></li>
        <li style='float:none; display: inline-block;'><%= link_to "Proposal", proposal_path %></li>
        <li style='float:none; display: inline-block;'><%= link_to "Wedding Party", wedding_party_path %></li>
        <div class="navbar-header" style='float:none; display: inline-block;'>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="font-family: 'Pacifico', cursive; font-size: 2em;float:none; display: inline-block;"> Jill + Ryan</a>
    </div>
        <li style='float:none; display: inline-block;'><%= link_to "RSVP", enter_code_path %></li>
        <li style='float:none; display: inline-block;'><%= link_to "Registry", registry_path %></li>
        <li style='float:none; display: inline-block;'><%= link_to "Guestbook",  guestbooks_path %></li>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :confirmation_code %><br>
    <%= f.text_field :confirmation_code %>
  </div>
  <div class="field">
    <%= f.label :can_attend %><br>
    <%= f.check_box :can_attend %>
  </div>
  <div class="field">
    <%= f.label :num_attending %><br>
    <%= f.number_field :num_attending %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/enter_code.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-12' style="font-family: 'Pacifico', cursive; font-size: 3em;">RSVP to the wedding!</div>
  </div>
<br />

<% if flash[:notice] %>
<p class='error'>
  <div class="alert alert-danger" role="alert">
    <%= flash[:notice] %>
  </div>
</p>

<% end %>

<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <li></li>
      
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :confirmation_code %><br>
    <%= f.text_field :confirmation_code, :class => 'form-control' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Start RSVP" %>
  </div>
<% end %>


</div>

app/views/rsvps/give_rsvp.erb
<h1>Set RSVP</h1>

<%= render 'form' %> 

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<div class='container'>   
  <div class='page-header'>
     <h1 style="font-family: 'Pacifico', cursive;">RSVPs</h1>
  </div>
</div>

<div class='container'>
  <p>After you have received your invitation, please <%= link_to 'Click on this button to RSVP to the wedding', 'give', :class => 'btn btn-default' %></p>
</div>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rsvp.name %>
</p>

<p>
  <strong>Confirmation code:</strong>
  <%= @rsvp.confirmation_code %>
</p>

<p>
  <strong>Can attend:</strong>
  <%= @rsvp.can_attend %>
</p>

<p>
  <strong>Num attending:</strong>
  <%= @rsvp.num_attending %>
</p>

<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/update_rsvp.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-12' style="font-family: 'Pacifico', cursive; font-size: 3em;">RSVP to the wedding!</div>
  </div>
<br />

<% if flash[:notice] %>
<p class='error'>
  <div class="alert alert-danger" role="alert">
    <%= flash[:notice] %>
  </div>
</p>

<% end %>

<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :name,  "Name(s) of attendees" %><br />
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :can_attend, 'Accepts with pleasure'%><br />
    <%= f.check_box :can_attend %>
  </div>
  <div class="field">
    <%= f.label :can_attend, 'Declines with regret'%><br />
    <%= check_box_tag 'Unable to attend' %>
  </div>
  <div class="field">
    <%= f.label :num_attending, "Number attending" %><br />
    <%= f.number_field :num_attending, min: 0, max: @rsvp.max_attending, value: @rsvp.num_attending, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :messages, "Messages (dietary restrictions, song requests, something you want to tell Jill and/or Ryan, etc.)" %><br />
    <%= f.text_area :messages, :class => 'form-control' %>
  </div>
  <div class="actions">
  <br />
    <%= f.submit "Finish RSVP" %>
  </div>
<% end %>

</div>

app/views/static_page/_newsitem.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>
  <%= title %> - <%= date %>
  </div>
  <div class='panel-body'>
    <%= news.html_safe %>
  </div>   


</div>

app/views/static_page/_weddingpartylistitem.html.erb
<li class='list-group-item'>
  <div class='media'>
    <div class='pull-left'>
      <div class='thumbnail'>
        <img src='<%= "/assets/wedding-party-#{name.downcase}.jpg" %>' alt='<%= name %> <%= role %>'/>
      </div>
    </div>
    <div class='media-content'>
      <h3><%= name %>  <small> <%= role %></small></h3>
      <p>
        <%= description %>
      </p>
    </div>
  </div>
</li>

app/views/static_page/index.html.erb
<div class='jumbotron' style='background: url(/assets/jumbotron.jpg) no-repeat; background-position: center;'>
    <div class='container'>
      <div class='row'>
        <div class='col-lg-12'>
           <p style="font-family: 'Pacifico', cursive; font-size: 5em;">Jill & Ryan are getting married!</p>
        </div>
      </div>
      <div class='row'>
        <div class='col-lg-8'>
        </div>
        <div class='col-lg-6'>
           <p style="font-family: 'Pacifico', cursive; font-size: 5em;">October 31, 2015</p>
        </div>
      </div>
      <div class='row'>
	    <div class='col-lg-12'>
	            <br /><br /><br /><br /><br /><br /><br /><br /><br />
	    </div>
	  </div>
	  <div class='row'>
	    <div class='col-lg-8'>
	    </div>
	    <div class='col-lg-4'>
	       <p>We want you to <%= link_to "Sign the guestbook", guestbooks_path, :class => 'btn btn-default' %></p>
	    </div>
	  </div>
	</div>
</div>  

<div class='container'>
  <div class='page-header'>
    <h1 style="font-family: 'Pacifico', cursive;">Wedding News</h1>
  </div>

<%= render partial: 'newsitem', 
            locals: {   
              :title => 'Invitations have gone out', 
              :date => 'Aug 24, 2015', 
              :news => "We have just sent out our invitiations.  Please watch your mail for the invite and either go to <a href='/enter_code'>this page to submit your RSVP</a>, or mail back the RSVP card."
            }
%>

<%= render partial: 'newsitem', 
            locals: {   
              :title => 'Location', 
              :date => 'May 5, 2015', 
              :news => "We have picked a location for the wedding!  It will be at <a href='http://www.beckerfarms.com/#!vizcarravineyards/cee5'>Becker Farms/Vizcarra Vineyards</a> on October 31, 2015.  Save the dates will be heading out soon!  --R"
            }
%>

<%= render partial: 'newsitem', 
            locals: {   
              :title => 'Wedding Party', 
              :date => 'Jan 3, 2015', 
              :news => "Our entire wedding party has been notified who they are, and their descriptions are now up on the wedding party page! --R"
            }
%>

<%= render partial: 'newsitem', 
            locals: { 
              :title => 'Guest List', 
              :date => 'Nov 6, 2014', 
              :news => "We have nailed down most of the wedding party and are finalizing the guest list now!  Things are moving along nicely :) --R"
            }
%>

<%= render partial: 'newsitem', 
            locals: { 
              :title => 'Getting the site up', 
              :date => 'Nov 3, 2014', 
              :news => "I am developing the site from scratch so hopefully you guys (and especially Jill, am I right? ;) ) think it is cool.  We don't have a date set so any references to any dates right now are just temporary"
            }
%>

  </div>

app/views/static_page/proposal.html.erb
<div class='container'>   
  <div class='page-header'>
     <h1 style="font-family: 'Pacifico', cursive;">The Proposal <small style='font-family: "Helvetica Neue", Helvetica, Arial, sans-serif'>  - October 13, 2014</small></h1>
  </div>

  <div class='container'>
  <p>Ryan + Jill met at Rosie + Chris' wedding in May of 2012.  He decided to call Jill one day and their friendship took off.  February of 2013, Ryan and Jill started dating and set a date for her to move down to Ryan's place in VA.  She moved down in August of 2013 and has lived with him ever since.</p>
    <p>On Columbus Day of 2014, Ryan knew that he was going to propose to Jill.  He was nervous all day and had just asked Jill's mom the day before if her family would approve of him asking her.  To prepare, he set up hundreds of candles around the house and pointed her towards where he was on a knee.  Following are some of the candles that were set up.</p>

    <div class="row">
      <div class="col-lg-12">
        <a href="#" class="thumbnail">
          <img src="/assets/proposal-1.jpg" />
        </a>
      </div>
      </div>
      <div class='row'>
      <div class="col-lg-6">
        <a href="#" class="thumbnail">
          <img src="/assets/proposal-2.jpg" />
        </a>
      </div>
      <div class="col-lg-6">
        <a href="#" class="thumbnail">
          <img src="/assets/proposal-3.jpg" />
        </a>
      </div>
    </div>
    <p>Don't worry, there was a fire extinguisher on hand in case things went awry.</p>
    <p>Since Jill had constantly told Ryan about other people having to re-take photos of proposals, Ryan decided to take a couple of videos to cut together into the following proposal video:</p>

  </div>  


  <div class='embed-responsive embed-responsive-16by9'>
  <iframe width="560" height="315" src="//www.youtube.com/embed/X_l56UIe_TA" frameborder="0" allowfullscreen></iframe>
  </div>
<br />
  <p>
        Now they are on their way to their happily ever after!
  </p>    
</div>

app/views/static_page/registry.html.erb
<div class='container'>   
  <div class='page-header'>
     <h1 style="font-family: 'Pacifico', cursive;">Registry</h1>
  </div>
</div>



<div class='container'>
<div class='row'>
  <p>
    We are very thankful that we have you in our lives.  Thank you in advance (and forever) for anything that you get us.  Currently, we are registered at Williams-Sonoma, Target, and Amazon.  
  </p>
</div>
  <div class='row'>
    <div class='col-lg-6' style='text-align: right;'>
        <a href='https://www.amazon.com/gp/registry/wedding/2SGIK45MIEBFV' target='_blank'>
            <img src='http://g-ecx.images-amazon.com/images/G/01/x-locale/communities/wishlist/uwl/UWL_SWF_shims._V368675346_.png' />
        </a>
    </div>
    <div class='col-lg-6' style='text-align: left; vertical-align: center'>
     <a href='https://www.amazon.com/gp/registry/wedding/2SGIK45MIEBFV' target='_blank'>
          <br />
          <br />
          <br />
          <br />
          <h4 class='media-heading'>Jill and Ryan's Amazon Wedding Registry</h4>
      </a>
    </div>
  </div>
  <div class='row'>
    
    <div class='col-lg-6' style='text-align: right;'>
        <a href='https://secure.williams-sonoma.com/registry/nxn7v66cqs/registry-list.html' target='_blank'>
            <img src='http://www.buyvia.com/i/2014/06/logo-31.png' />
        </a>
    </div>
    <div class='col-lg-6' style='text-align: left; vertical-align: center'>
     <a href='https://secure.williams-sonoma.com/registry/nxn7v66cqs/registry-list.html' target='_blank'>
          <br />
          <br />
          <br />
          <br />
          <br />
          <h4 class='media-heading'>Jill and Ryan's Williams-Sonoma Wedding Registry</h4>
      </a>
    </div>
  </div>    
  <div class='row'>
    
    <div class='col-lg-6' style='text-align: right;'>
        <a href='http://www.target.com/gift-registry/giftgiver?registryId=a-3ZrfsCP9Da-2nSghow6w&registryType=WEDDING' target='_blank'>
            <img src='http://cf.juggle-images.com/matte/white/280x280/target-logo-primary.jpg' />
        </a>
    </div>
    <div class='col-lg-6' style='text-align: left; vertical-align: center'>
     <a href='http://www.target.com/gift-registry/giftgiver?registryId=a-3ZrfsCP9Da-2nSghow6w&registryType=WEDDING' target='_blank'>
          <br />
          <br />
          <br />
          <br />
          <br />
          <h4 class='media-heading'>Jill and Ryan's Target Wedding Registry</h4>
      </a>
    </div>
  </div>   
</div>

app/views/static_page/rsvp_can_attend.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-12' style="font-family: 'Pacifico', cursive; font-size: 3em;">RSVP submitted!</div>
  </div>
<br />
  <p>
Thank you for rsvping!  We are looking forward to seeing you at our wedding.  If you would like to change anything about your RSVP, please go through the RSVP process again to update your information.  For any questions/help, please email Ryan (ry.gimmy@gmail.com) or Jill (JillianNAnderson@yahoo.com).
</p>
</div>

app/views/static_page/rsvp_cannot_attend.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-12' style="font-family: 'Pacifico', cursive; font-size: 3em;">RSVP submitted!</div>
  </div>
  <br />
  <p>
Thank you for rsvping!  We are sorry that you cannot attend, but are thankful that you have been a big part of our lives.  If you would like to change anything about your RSVP, please go through the RSVP process again to update your information.  For any questions/help, please email Ryan (ry.gimmy@gmail.com) or Jill (JillianNAnderson@yahoo.com).
</p>
</div>

app/views/static_page/wedding_details.html.erb
<div class='container'>   
  <div class='page-header'>
     <h1 style="font-family: 'Pacifico', cursive;">Wedding Details</small></h1>
  </div>
</div>

<div class='container'>
  <p>When should we be there?<br /> <b>October 31, 2015 at 4pm</b></p>
  <p>Where will the ceremony and reception be? <br />
  	<b><a href='http://www.beckerfarms.com/#!vizcarravineyards/cee5'>Becker Farms/Vizcarra Vineyards</a><br />
    3724 Quaker Rd.<br />
    Gasport NY, 14067</b>
  </p>

  <p>Where can we stay?<br /> <b>Best Western Plus in Lockport.  Mention the Anderson/Gimmy wedding to get a room in the block.</b></p>
  <p>
  <b>
  BEST WESTERN PLUS Lockport Hotel<br />
515 S Transit Street<br />
Lockport, New York, 14094-5911, US<br />
  </b>
  </p>

<p>Will transportation be provided?<br /> <b>There will be a bus shuttling people to and from the wedding venue starting around 2pm.</b></p>
  
  <h3 style="font-family: 'Pacifico', cursive;" >Directions to the venue</h3>
  
  	<h4>From 104 West</h4>
  <p>	
  <ul>
	<li>Head west on NY-104 West, 46.2 miles.</li>
	<li>Turn left onto Quaker Road.</li>
	<li>Destination will be on the right</li>
   </ul>
 </p>
 
<h4>From Best Western Plus</h4>
 
 <p>
 <ul>
 <li>Head north on South Transit Street toward Lincolnshire Drive 1.5 miles</li>
 <li>Turn right onto Grand Street, 0.2 miles</li>
 <li> Grand Street turns left and becomes Clinton Street, 1.0 mile</li>
 <li>  Clinton St turns left and becomes NY-78 N/Lake Avenue, 1.2 miles</li>
 <li>  Turn right onto Slayton Settlement Road, 5.6 miles</li>
 <li>  Turn left onto Quaker Road.  Destination will be on the left </li>
 </ul>
  </p>

</div>